apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: truecommand-data
  name: truecommand-data
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
status: {}
